from typing import List, Type, Any

from fairxai.explain.adapter.generic_explainer_adapter import GenericExplainerAdapter
from fairxai.logger import logger


class ExplainerManager:
    """
    Operational module of the library.

    Responsibilities:
    - Analyzes the dataset and shows compatible explainers
    - Executes the pipeline of selected explainers
    - Manages visualization of results
    - Provides guided wizards for configuration
    """

    def __init__(self, project):
        # Store the project reference containing dataset, model, and available explainers
        self.project = project
        logger.info("ExplainerManager initialized.")

    # -----------------------------
    # Core functionality
    # -----------------------------

    def list_available_explainers(self) -> List[str]:
        """
        Returns all available explainers in the project.

        Returns
        -------
        List[str]
            List of all explainer class names available in the project.
        """
        # Extract and return the names of all explainer classes registered in the project
        return [e.__name__ for e in self.project.explainers]

    def list_compatible_explainers(self) -> List[str]:
        """
        Returns only explainers compatible with the dataset and model.

        Returns
        -------
        List[str]
            List of compatible explainer class names.
        """
        # Query the project for explainers that match the current dataset and model types
        compatible = self.project.get_compatible_explainers()
        return [e.__name__ for e in compatible]

    def run_explainer(self, explainer_cls: Type[GenericExplainerAdapter], instance: Any):
        """
        Executes an explainer and visualizes the result.
        Blocks execution if not compatible.

        Parameters
        ----------
        explainer_cls : Type[GenericExplainerAdapter]
            The explainer class to execute.
        instance : Any
            The instance to explain.

        Returns
        -------
        GenericExplanation
            The generated explanation object.
        """
        logger.debug(f"Running explainer {explainer_cls.__name__}...")

        # Generate the explanation by delegating to the project's run_explanation method
        # This method handles compatibility checks and explainer instantiation
        explanation = self.project.run_explanation(explainer_cls, instance)
        logger.info(f"Explanation generated by {explainer_cls.__name__}. Visualizing...")

        # Automatically visualize the generated explanation
        explanation.visualize()
        return explanation

    # -----------------------------
    # Wizard-guided interface
    # -----------------------------

    def run_wizard(self):
        """
        Interactive wizard that guides the user in selecting dataset, model and explainer.

        This method orchestrates the entire wizard flow by delegating specific tasks
        to dedicated private methods.

        WIZARD FLOW:
        1. Display project info (dataset type, model type)
        2. Check for compatible explainers (if none, exit)
        3. User selects an explainer from the compatible list
        4. User selects/confirms an instance to explain
        5. Execute the explanation and visualize results

        Each step can be cancelled by the user, causing a graceful exit.
        """
        logger.info("Starting FAIR-XAI Explainer Wizard")
        print("\n=== FAIR-XAI EXPLAINER WIZARD ===")

        # STEP 1: Show dataset and model types to user
        self._display_project_info()

        # STEP 2: Get list of compatible explainers
        compatible = self.list_compatible_explainers()
        if not compatible:
            # Early exit if no compatible explainers found
            logger.warning("No compatible explainers found for current dataset and model")
            print("No compatible explainers found.")
            return

        # STEP 3: User selects an explainer from the compatible list
        explainer_cls = self._select_explainer(compatible)
        if explainer_cls is None:
            # User cancelled or invalid selection - exit wizard
            return

        # STEP 4: User selects/confirms an instance to explain
        instance = self._select_instance()
        if instance is None:
            # User cancelled instance selection - exit wizard
            return

        # STEP 5: Execute the explanation and display results
        self._execute_explanation(explainer_cls, instance)

    def _display_project_info(self):
        """
        Displays information about the project's dataset and model.

        Prints the dataset type and model type to the console.

        WIZARD STEP 1: Inform the user about current project configuration
        """
        # Retrieve dataset and model types using getattr with fallback to 'Unknown'
        dataset_type = getattr(self.project.dataset, 'type', 'Unknown')
        model_type = getattr(self.project.blackbox, 'type', 'Unknown')
        logger.debug(f"Project info - Dataset type: {dataset_type}, Model type: {model_type}")

        # Display to console for user visibility
        print(f"Dataset type: {dataset_type}")
        print(f"Model type: {model_type}\n")

    def _select_explainer(self, compatible: List[str]) -> Type[GenericExplainerAdapter]:
        """
        Shows compatible explainers and allows the user to select one.

        Parameters
        ----------
        compatible : List[str]
            List of compatible explainer names.

        Returns
        -------
        Type[GenericExplainerAdapter] or None
            The selected explainer class, or None if selection fails.

        WIZARD STEP 3: Present compatible explainers and get user selection
        """
        # Display numbered list of compatible explainers
        print("Compatible explainers:")
        for i, name in enumerate(compatible):
            print(f"  [{i}] {name}")

        try:
            # Prompt user to enter the index of desired explainer
            idx = int(input("\nSelect explainer → "))

            # Validate the selected index is within valid range
            if idx < 0 or idx >= len(compatible):
                logger.warning(f"Invalid explainer index selected: {idx}")
                print("Invalid index.")
                return None

            # Retrieve the selected explainer name and find its class
            selected_name = compatible[idx]
            logger.info(f"User selected explainer: {selected_name}")
            return self._get_explainer_class(selected_name)
        except (ValueError, IndexError) as e:
            # Handle non-numeric input or index errors
            logger.error(f"Error in explainer selection: {e}")
            print("Invalid selection.")
            return None

    def _get_explainer_class(self, explainer_name: str) -> Type[GenericExplainerAdapter]:
        """
        Retrieves the explainer class given its name.

        Parameters
        ----------
        explainer_name : str
            Name of the explainer to retrieve.

        Returns
        -------
        Type[GenericExplainerAdapter]
            The corresponding explainer class.
        """
        # Search through project explainers and return the one matching the given name
        return next(e for e in self.project.explainers if e.__name__ == explainer_name)

    def _select_instance(self) -> Any:
        """
        Shows an example instance and requests user confirmation.

        Displays the first row of the dataset as an example and asks
        the user to confirm if they want to explain this instance.

        Returns
        -------
        Any or None
            The selected instance if confirmed, None otherwise.

        WIZARD STEP 4: Present an example instance and get user confirmation
        """
        print("\nExample instance to explain (first row of dataset):")

        # Get the first row from the dataset as the example instance
        instance = self.project.dataset.df.iloc[0]
        print(instance)

        # Ask user for confirmation to proceed with this instance
        confirm = input("\nDo you want to explain this instance? [y/N] ")
        if confirm.lower() != "y":
            # User declined - cancel the wizard
            logger.info("User cancelled instance selection")
            print("Cancelled.")
            return None

        # User confirmed - proceed with this instance
        logger.info("Instance confirmed for explanation")
        return instance

    def _execute_explanation(self, explainer_cls: Type[GenericExplainerAdapter], instance: Any):
        """
        Executes the explainer on the selected instance and displays results.

        Parameters
        ----------
        explainer_cls : Type[GenericExplainerAdapter]
            The explainer class to execute.
        instance : Any
            The instance to explain.

        WIZARD STEP 5: Run the selected explainer on the confirmed instance
        """
        logger.info(f"Executing explainer: {explainer_cls.__name__}")
        print("\nExecuting explainer...")

        # Call the core run_explainer method which generates and visualizes the explanation
        self.run_explainer(explainer_cls, instance)

        logger.info("Explanation completed successfully")
        print("\nExplanation completed.")
